# Import necessary modules and classes from the 'lagent' library.
from lagent.actions import ActionExecutor, GoogleSearch, PythonInterpreter
from lagent.agents import ReAct
from lagent.llms import HFTransformer
from lagent.llms.meta_template import INTERNLM2_META as META

# Initialize the HFTransformer-based Language Model (llm) and
# provide the model name.
llm = HFTransformer(path='internlm/internlm2-chat-7b', meta_template=META)

# Initialize the Google Search tool and provide your API key.
search_tool = GoogleSearch(api_key='Your SERPER_API_KEY')

# Initialize the Python Interpreter tool.
python_interpreter = PythonInterpreter()

# Create a chatbot by configuring the ReAct agent.
# Specify the actions the chatbot can perform.
chatbot = ReAct(
    llm=llm,  # Provide the Language Model instance.
    action_executor=ActionExecutor(actions=[python_interpreter]),
)
# Ask the chatbot a mathematical question in LaTeX format.
response = chatbot.chat(
    '若$z=-1+\\sqrt{3}i$,则$\frac{z}{{z\\overline{z}-1}}=\\left(\\ \\ \right)$')
# Print the chatbot's response.
print(response.response)  # Output the response generated by the chatbot.
